### ISSUE TITLE
Eval/Validation CER

### ISSUE THREAD

**Issue by whisere** [Shreeshrii/tesstrain-ben#1]
Hello I tried this branch instead of the original for plotting after seeing this post https://github.com/tesseract-ocr/tesstrain/issues/239, but EvalCER and ValidationCER are both empty so only plotting training CER but not the Eval/validation CER? Thanks.

**Comment by Shreeshrii** [comment]
Eval cer will be plotted only after the eval process run by training. You can review the log file to verify that training has been run long enough to run lstmeval.

**Comment by whisere** [comment]
Many thanks! May I ask what is the command to run eval? I use the default MAX_ITERATIONS, it should be long enough?

**Comment by whisere** [comment]
I used this command: nohup make training MODEL_NAME=model_name START_MODEL=eng TESSDATA=../tessdata_best MAX_ITERATIONS=10000 > plot/TESSTRAIN.LOG &
Thanks.

**Comment by whisere** [comment]
I can't find any lstmeval in the log  (after training is finished) or in the scripts, I don't think this eval is run during the training, perhaps that needs to be run separately?

**Comment by Shreeshrii** [comment]
See https://github.com/Shreeshrii/tess5train-fonts

Compare the plot files for finetuning and replacing a layer and you can see that eval does run for replace a layer training.

https://github.com/Shreeshrii/tess5train-fonts/blob/main/data/engFineTuned/plots/engFineTuned-LOG-2.png

https://github.com/Shreeshrii/tess5train-fonts/blob/main/data/engLayer/plots/engLayer-LOG-2.png
